### ISSUE TITLE
Landing page children

### ISSUE THREAD

**Issue by DollyTheSau** [aau-giraf/foodplanner#19]
## Description for child pages jf. figma 16/10.
Need 2 pages. 
Meal page
See meal with its ingredients that needs to be moveable.

## Need to be done before working on the affected subtasks
- [x] #44 

## Subtask

- [x] #41 
- [x] Create Child landing page using widget #41
- [x] Create CTA to See meal page 
- [x] #42 
- [x] Iterate over the #42 widget for every ingredient in the meal.
- [x] Make them dragable /moveable
- [x] Create a hint button/icon
- [x] Connect login - with role = child --> child-landingpage. done after #44 

End goal of the child landing page.
![Image](https://github.com/user-attachments/assets/7f895f34-fd39-4353-9a2f-546e830276d7)
