### ISSUE TITLE
Landing page Teacher

### ISSUE THREAD

**Issue by JacobStokholms** [aau-giraf/foodplanner#31]
## Description for Jf figma. 16/10
Need a landing page for teachers where the teacher can see every class. 
When clicked on a class the students should show.
When clicked on a student the students meal should show.

## Need to be done before working on the affected subtasks.
- [x] #41 In #19 

## Subtask

- [x] Create Teacher landing page
- [x] Retrieve all classes from the database. (use distinct if an endpoint does not exist.). 
- [x] Retrieve all student from the chosen class.
- [x] Search for a student. Student must be highlighted in the list.
- [x] Creater teacher meal page
- [x] CTA from a student to meal page for teachers using widget #41 
- [x] Connect login - with role = teacher--> teacher-landingpage. 
- [x] Integrate the footer if it exist. Otherwise create it / design it as the figma

![Image](https://github.com/user-attachments/assets/cb8b08c2-5dcf-4a62-87e1-39227b015894)
