### ISSUE TITLE
Landing page forældre

### ISSUE THREAD

**Issue by JacobStokholms** [aau-giraf/foodplanner#32]
## Description for Jf. figma 16/10
Need a landing page for parents  when logged in the system.
When logged in, the meal for their child must be shown for the day if it exists. 

## Need to be done before working the affected subtasks.
- [x] #41 In #19 
- [x] #44 

## Subtask
- [x] Create a landing page for parents consisting of two components.
- [x] 1. #41  that shows if there exist a meal
- [x] 2. An empty box if no meal exist. (Integrate this component that is created by group 10)
- [x] Integrate the footer if it exist. Otherwise create it / design it as the figma
- [x] CTA on datetime - open datepicker ( check for the datepicker from group 10)
- [x] CTA to create a new meal ( Check for group 10)
- [x] CTA to see feedback
- [x] Connect login - with role Parent= parent --> parent-landingpage. #44 

![Image](https://github.com/user-attachments/assets/71513f6f-f01d-455b-b5fe-c335233b625b)
