### ISSUE TITLE
Feedback function teacher - parent Frontend

### ISSUE THREAD

**Issue by JacobStokholms** [aau-giraf/foodplanner#64]
## Description for feedback function jf. figma 20/11.
We need a chat between a parent and a teacher.
The chat should be one long chat with small marks between days.

## Todo
- [x] Add feedback page to footer
- [x] Display a message from both parent and teacher in order by date asc.
- [x] Add send message.
- [ ] Load thread depending on which teacher wrote that day.

![Image](https://github.com/user-attachments/assets/77f95894-56b6-4870-8bd7-66d75f271f45)
